### ISSUE TITLE
Add fixes for CREATE VIEW and CREATE TRIGGER

### ISSUE THREAD

**Issue by oising** [IowaComputerGurus/Azure-DevOps-Extensions#11]
these statements need to be wrapped in EXEC(' ... ') since dotnet ef migrations script generates invalid sql (create view/create trigger need to be the first line in a batch)

**Comment by mitchelsellers** [comment]
Can you provide examples of what migrations generate invalid scripts, I'm testing against .NET Core 3.1 and not seeing issues.

I created #13 to document this more

**Comment by mitchelsellers** [comment]
This has been fixed by Microsoft in EFCore 5.0
