### ISSUE TITLE
Add parameters for specifying DbContext

### ISSUE THREAD

**Issue by bmallen1** [IowaComputerGurus/Azure-DevOps-Extensions#12]
For instances where a project has more than one DbContext, it would be preferable to specify the name of the context as such,

EDIT: added a space

$contents = "dotnet ef migrations script -p " + $input_contextProjectDirectory + " -o " + $input_scriptTargetLocation;
        if($input_startupProjectDirectory){
            $contents = $contents + " --startup-project " + $input_startupProjectDirectory;
        }
        if($input_createAsIdempotent){
            $contents = $contents + " -i"
        }
if($input_dbContext){
            $contents = $contents + " -context " + $input_dbContext
        }

**Comment by mitchelsellers** [comment]
@bmallen1 Great suggestion, we will work this into the next release!

**Comment by coldacid** [comment]
@mitchelsellers when will that next release be?

**Comment by mitchelsellers** [comment]
@coldacid I have this on the development plate for Friday this week.  Hope to have it rolled out by Monday/Tuesday next week at the latest.  

Sorry for the delay in getting this out.

**Comment by coldacid** [comment]
@mitchelsellers Will it include support for UPDATE and IDENTITY_INSERT transforms as well?

**Comment by mitchelsellers** [comment]
Do you have details on what is needed for that?

**Comment by coldacid** [comment]
Essentially, blocks which contain a `SET IDENTITY_INSERT [TableName] ON;` statement, or any of the below-listed statements, needs to be wrapped:

- `UPDATE`
- `CREATE` or `ALTER PROCEDURE`
- `CREATE` or `DROP VIEW`
- `ALTER TABLE`
- and of course the already-covered `CREATE UNIQUE INDEX`.

**Comment by mitchelsellers** [comment]
Yup!  We will include that
