### ISSUE TITLE
Additional Wrapping for Idempotent Bug

### ISSUE THREAD

**Issue by mitchelsellers** [IowaComputerGurus/Azure-DevOps-Extensions#13]
Extracted from the discussion with @coldacid in #12

Essentially, blocks which contain a `SET IDENTITY_INSERT [TableName] ON;` statement, or any of the below-listed statements, needs to be wrapped:

- `UPDATE`
- `CREATE` or `ALTER PROCEDURE`
- `CREATE` or `DROP VIEW`
- `ALTER TABLE`
- and of course the already-covered `CREATE UNIQUE INDEX`.

_Originally posted by @coldacid in https://github.com/IowaComputerGurus/Azure-DevOps-Extensions/issues/12#issuecomment-645554162_

**Comment by mitchelsellers** [comment]
I've been doing some additional testing on this, and the currently generated scripts by EF Core seem to be fine for migrations with data as well as alter tables and the idempotent scripts are still working as desired.

Do you have examples of a migration, created with the idempotent flag that has the "wrong" syntax?  Just so I can validate against what our models are doing?

**Comment by coldacid** [comment]
No examples that I can share, unfortunately, but we discovered that without `EXEC` migrations that updated data seeded through the context itself would fail.

**Comment by mitchelsellers** [comment]
Interesting we have been testing with 12 different projects what we have. 

All using HasData() 

All inserts and updates are working 

Wrapping what is generated in our case would break

**Comment by mitchelsellers** [comment]
Microsoft has fixed this with .NET Core 5.0 - Closing this issue.
